Avipatel1107/COSC4P02

- coursemix/src/components/Navbar.jsx
Removed if statement in NavBar which caused navbar to turn into the spinner component when loading. This fixed the "bug" lololol
> fixed spinner rendering bug

- coursemix/src/app/protected/course-registration/page.js
- coursemix/src/app/protected/course-reviews/page.js
- coursemix/src/app/protected/grades/page.js
- coursemix/src/app/protected/profile/page.js
Created profile page that allows users to edit their profile.
> Created profile page

- coursemix/src/app/protected/My-Courses/page.js
- coursemix/src/app/protected/course-registration/page.js
- coursemix/src/components/Navbar.jsx
Added a dropdown menu for Course Registration where users can register for courses and view enrolled courses, the my courses page allows for users to un-enroll courses which are reflected on the dashboard and the database as well, Also got the duration filter working and when a user searches for a course, added functionality where input can include capital letters and space between course codes.
> My courses

- coursemix/src/app/protected/course-registration/page.js
- coursemix/src/components/ConfirmDialog.jsx
Fixed by implementing logic to check for conflicting overlaps in courses, added a confirmation box that appears if there is a conflict. This way users can still be registered in overlapping courses as Brock University does allow for this to happen.
> Fixed issue where users could register for overlapping courses

- coursemix/src/app/forgot-password/page.jsx
- coursemix/src/components/Register.jsx
- coursemix/src/components/RequireAuth.jsx
- coursemix/src/components/SignIn.jsx
- coursemix/src/components/TimeTable.jsx
Removed if statements from all files, these are redundant now that we have a loading.js file anyways.
> Fix for infinite loading bug

- coursemix/src/app/protected/course-reviews/page.js
> Placeholder for reviews page 

- coursemix/src/components/SignIn.jsx
Modified Signin Component to stop infinite sign in bug where users get stuck on the sign in page infinitely.
> Fixing Infinite Sign In Bug

- coursemix/components/Footer.tsx
> Fixing terms of service route in footer.

- coursemix/app/(auth-pages)/sign-up/page.tsx
- coursemix/components/course-registration/CourseSearch.tsx
- Added check so users can only signup with @brocku emails
- Added a popular courses filter
- Added a filter by duration
> Added register and filter updates

- coursemix/app/(footer-pages)/about-us/page.tsx
- coursemix/app/(footer-pages)/contact/metadata.ts
- coursemix/app/(footer-pages)/contact/page.tsx
- coursemix/app/(footer-pages)/features/page.tsx
- coursemix/app/(footer-pages)/layout.tsx
- coursemix/app/(footer-pages)/privacy-policy/page.tsx
- coursemix/app/(footer-pages)/terms-of-service/page.tsx
- coursemix/app/(footer-pages)/testimonials/page.tsx
- coursemix/app/api/contact/route.ts
- coursemix/components/about-us/TeamMember.tsx
- coursemix/components/about-us/index.ts
- coursemix/components/course-registration/CourseSearch.tsx
Implemented all footer pages, and created the contact form, made it functional.
> Footer pages

- coursemix/components/course-registration/CourseSearch.tsx
- Added comprehensive schedule conflict detection for course registration
- Introduced new state variables to manage course conflicts and enrollment process
- Implemented time and day parsing utilities for schedule comparison
- Created a modal to warn users about potential scheduling conflicts
- Enhanced enrollment flow with conflict checking before final registration
- Improved error handling and user feedback during course enrollment
> Implement course schedule conflict detection and enrollment handling

- coursemix/components/course-registration/CourseSearch.tsx
- Improved course search algorithm to handle more complex query patterns
- Added support for parsing subject and number parts of course codes
- Implemented dynamic result limit based on query specificity
- Enhanced exact match prioritization for precise course code searches
- Optimized search query generation to cover multiple input variations
> Enhance course search query matching and result filtering

- coursemix/app/(user-pages)/protected/academic-progress/page.tsx
- coursemix/app/academic-progress-actions.ts
- coursemix/components/Navbar.tsx
- coursemix/components/academic-progress/CourseCard.tsx
- coursemix/components/academic-progress/CourseList.tsx
- coursemix/components/academic-progress/GradesList.tsx
- coursemix/package-lock.json
- coursemix/package.json
- coursemix/types/index.ts
- coursemix/utils/grade-utils.ts
Implemented academic progress page will full functionality.
Co-authored-by: Avi Patel<Avipatel1107@users.noreply.github.com>
Co-authored-by: Russel Salacup <dinosore-rs@users.noreply.github.com>
> Academic progress page

- coursemix/app/(user-pages)/protected/dashboard/page.tsx
- coursemix/components/Navbar.tsx
- coursemix/components/dashboard/UserProfile.tsx
- Updated Navbar from grades to academic progress for mobile devices
- adjusted the dashboard so that it dynamically fetches the current average and courses completed by a user from academic progress
> Navanddash

- coursemix/app/academic-progress-actions.ts
- coursemix/components/academic-progress/CourseCard.tsx
- coursemix/components/academic-progress/CourseList.tsx
- Added restrictions so students cad only add grades between 0-100
- fixed the course cards add grade button
- Added a functionality to put courses in progress
> Academicfix

- coursemix/app/(user-pages)/protected/profile/edit/page.tsx
- coursemix/components/dashboard/UserProfile.tsx
- Implement warning for program changes in profile edit page
- Add logic to clear student grades when program is changed
- Update UserProfile component with refined layout and styling
- Enhance user experience with clear warning about grade deletion
- Improve profile edit and display components with more informative UI
- Fixed Dashboard page program name bug where it was displaying oddly for longer program names
> Add program change warning and grade clearing mechanism

- coursemix/scripts/AddProgramRequirements.py
This script lets us add courses into program requirements table into our db making the process exponentially faster and easier to do.
> created a script to add courses to program reqs table

- coursemix/app/(footer-pages)/testimonials/page.tsx
- coursemix/app/(user-pages)/protected/profile/edit/page.tsx
added dark mode support to edit profile page and got rid of the user icon image in testimonials page
> edit profile page dark mode + testimonials page tweaks

- coursemix/app/(user-pages)/protected/dashboard/page.tsx
- coursemix/components/dashboard/Deadlines.tsx
- coursemix/components/dashboard/Timetable.tsx
- coursemix/components/dashboard/WeatherWidget.tsx
- Reorganized dashboard page to add right sidebar with all user deadlines, this scales based on users screen size
- added a projected grad date tracker and weather widget on left side bar, weather widget is functional, proj grad date tracker is not
- updated colors for course cards inside of time table to make them more vibrant and pop more in both light and dark mode and altered font colors
> Updated dashboard page

- coursemix/app/(user-pages)/protected/academic-progress/page.tsx
- coursemix/app/(user-pages)/protected/dashboard/page.tsx
- coursemix/app/(user-pages)/protected/profile-setup/page.tsx
- coursemix/app/(user-pages)/protected/profile/edit/page.tsx
- coursemix/app/(user-pages)/protected/profile/page.tsx
- coursemix/components/academic-progress/GradesList.tsx
- coursemix/utils/date-utils.ts
- Implemented algorithm to calculate graduation convocation ceremony tracker.
- Added this calculated date to the dashboard and academic progress page
- updated profile pages to account for adding a university start date
> Graduation tracker

- coursemix/app/(user-pages)/protected/course-reviews/page.tsx
Fixed alignment by adding a wrapper div
> fixed alignment for course reviews page

- coursemix/app/(user-pages)/protected/course-reviews/page.tsx
- coursemix/components/course-reviews/Discussions.tsx
- coursemix/components/course-reviews/ReviewForm.tsx
Discussions component prototype
Will make future changes
> Course reviews

- coursemix/components/Navbar.tsx
- coursemix/components/navigation-transitions/PageTransition.tsx
- coursemix/middleware.ts
Fixed this through refactoring middleware and improved user profile checking
> Fixing "Application error: client side exception" bug

- coursemix/app/(footer-pages)/contact/page.tsx
Update page.tsx
Contact us page:
Removed Facebook
Linked instagram and x accounts
> Linked Socials to page.tsx

- coursemix/app/(user-pages)/protected/course-registration/page.tsx
- coursemix/components/course-registration/CourseSearch.tsx
- coursemix/components/course-registration/CourseSuggestions.tsx
Implemented the course recommendations feature to the course registration page.
This takes into consideration electives, courses and their prerequisites, and suggests courses that it sees fit based on where you are in your degree progression. It prioritizes courses from early years to suggest to you so that you sequentially make your way through the degree.
> Course recommendations feature!

- coursemix/app/(footer-pages)/privacy-policy/page.tsx
> Privacy policy

- coursemix/app/(user-pages)/protected/academic-progress/page.tsx
- coursemix/components/academic-progress/CourseCard.tsx
- coursemix/components/academic-progress/CourseList.tsx
- If the user is registered for a credit that can only be filled by _one course,_ it will be automatically marked as In Progress and cannot be removed from such. Added new descriptions for this.
- To do: Add this functionality for 2 courses.
- To do: For Cluster credits / List credits, add a new JSON column to the database that lists all possible course codes, and/or classifies the credit as an elective.
May require review. Also, can we merge this without deleting the branch?
> Pull progress

- coursemix/app/(user-pages)/protected/academic-progress/page.tsx
- coursemix/components/academic-progress/CourseCard.tsx
- coursemix/components/academic-progress/CourseList.tsx
Reverts Avipatel1107/COSC4P02#83
> Revert "Pull progress"

- coursemix/components/course-reviews/ReviewForm.tsx
Fixed a bug where users could edit and delete each others reviews
> Fixed a bug where users could edit and delete each others reviews

- coursemix/app/page.tsx
Added "made for brock students by brock students to landing page"
> added text to landing page

- coursemix/__tests__/app/(footer-pages)/contact/page.test.tsx
- coursemix/__tests__/app/(footer-pages)/features/page.test.tsx
- coursemix/__tests__/app/(footer-pages)/testimonials/page.test.tsx
- coursemix/__tests__/app/(user-pages)/profile-setup/page.test.tsx
- coursemix/__tests__/app/(user-pages)/profile/page.test.tsx
contact, features, testimonials, profile, profile-setup
> Test Cases

- coursemix/__tests__/(footer-pages)/privacy-policy/page.test.tsx
Implemented test coverage for the privacy policy section within the footer components.
> Test: Implemented test coverage for the privacy policy section within footer components. 

- coursemix/__tests__/(footer-pages)/terms-of-service/page.test.tsx
Implemented test coverage for the terms of service section within the footer components
> Test: Implemented test coverage for the terms of service section within footer components 

- coursemix/__tests__/(user-pages)/protected/course-discussions/page.test.tsx
Implemented test coverage for the course discussions page.
> Test: Implemented test coverage for the course discussions page.
